### ISSUE TITLE
Hvac states doesnt work on NEST

### ISSUE THREAD

**Issue by denveronly** [jimz011/thermostat-card#1]
hi there i have this in my lovelace (im using nest thermostats with badnest integration)
if i dont use hvac states - thermostats are always in heat mode on
if i use hvac states - thermostat is always in idle mode (doesnt get orange when heating)

```
- type: custom:thermostat-card
              title: Nest 2
              entity: climate.upstairs_thermostat
              chevron_size: 100
              hvac:
                states:
                  'Off': 'idle'
                  'Cooling': 'cool'
                  'Heating': 'heating'
                attribute: hvac_action
```

nest has the following info about:

<img width="424" alt="Снимок экрана 2020-10-19 в 23 02 12" src="https://user-images.githubusercontent.com/66441516/96505741-3ed0da80-125f-11eb-99a3-012c27454200.png">

**Comment by denveronly** [comment]
okay all found
it should be like this one to work correctly

```
- type: custom:thermostat-card
              title: Nest 1
              entity: climate.dining_room_thermostat
              hvac:
                states:
                  'idle': 'off'
                  'Cooling': 'cool'
                  'heating': 'heat'
                attribute: hvac_action
```
